services:
  database:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 123124
      MYSQL_DATABASE: people
      MYSQL_USER: rocks
      MYSQL_PASSWORD: 123124
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - fullcyclerocks
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 5s
      timeout: 20s
      retries: 4

  application:
    build:
      context: ./nodejs
    image: a2martins/nodejs:latest
    container_name: app
    networks:
      - fullcyclerocks
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_PORT: 3306
      DATABASE: people
      DATABASE_USER: rocks
      DATABASE_PASSWORD: 123124
    volumes:
      - nodeapp:/usr/src/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 5s
      timeout: 20s
      retries: 4
      start_period: 40s
    restart: on-failure

  nginx:
    build:
      context: ./nginx
    image: a2martins/nginx:latest
    container_name: nginx_proxy
    networks:
      - fullcyclerocks
    ports:
      - "80:80"
    depends_on:
      application:
        condition: service_healthy

networks:
  fullcyclerocks:
    driver: bridge

volumes:
  dbdata:
  nodeapp:


